# -*- coding: utf-8 -*-






##dict of response for each type of intent
response = {
    "greet":["hey","hello","hi"],
    "goodbye":["bye","It was nice talking to you","see you","ttyl"],
    "affirm":["cool","I know you would like it"],
    "day_preference":["which day of conference ?"],
    "time_preference":["Do you have any time preference"],
    "events_link":['You can check all the events here <a href="https://conference.pydelhi.org/#schedule_table">PyDelhi events</a>'],
    "no_events":["No events found"],
    "intro":["I am event bot for pydelhi, I can find you event details in minutes"],
    "FAQ":["This question looks like a frequently asked question. Please visit our FAQ link here (example) to find useful information"],
    "Mission-Statement":["School mission statements represent a useful source of data for gaining access to the school perspective on matters"],
    "inspire":['By providing experiences for teachers to grow, teachers become more committed to the schools mission. When giving the opportunity to lead, teachers are vested and want to see their work be successful. As the administration relinquishes control to the teacher and shows trust, teachers become more creative and willing to take risks. The classroom teacher will try new approaches to instruction, provide more assistance to their students, and be more flexible. By granting more freedom and independence teachers are more likely to have buy-in to the schools mission. This idea is backed up by Terry (2000) when he states - principals should allow their teachers the freedom to be creative and take risks.  To enhance these experiences, administrators need to recognize teachers and their accomplishments. With the opportunity to grow as a professional and be recognized for their efforts, teachers will become more empowered and willing to explore future experiences leading to continued growth. For further information visit "<a href="http://www.teachhub.com/working-together-administrators-role-empowering-teachers"></a>'],
    "familiar":['The relationship between teachers and administrators visions is important. Administrators visions tend to encompass the whole system; their vision is an organizational vision. Teachers visions appear to focus primarily on the individual or personal actions for school change. However, closer examination of the two may reveal that both groups of educators are attending to different aspects of the same vision. It is because of the differences in teachers and administrators perspectives that makes the development of a shared vision important. For further information visit "<a href="http://www.sedl.org/change/issues/issues23.html"></a>'],
    "consensus":['School administrators who have developed a shared vision with their faculty have created common ground that serves to facilitate or promote action toward the realization of their vision. Although, they may begin with a personal vision to forge a shared vision with their staff, the leaders communication of the vision is such that it attracts others to join in the endeavor to attain it. School leaders not only must have a vision of their school or district but also the skills to communicate that vision to others, in developing a shared one. They invite and encourage others to participate in determining and developing this shared vision. The process promotes collegial and collaborative relationships. Although the process needed for developing a shared vision may be time consuming, the resulting shared commitment to the realization of the vision is the reward for the time and energy invested in such a collaborative process. Involve critical individuals. The individuals or groups identified as constituencies include those that are the most critical, both inside and outside, to a school or district. These critical individuals can be those who are essential, such as a representative of a major business in the community and those people who tend to judge severely, such as the consistently vocal parent. Consider the major expectations or interests of these critical constituents as well as any threats or opportunities that may originate from these groups or individuals. Educators should involve individuals such as students, parents, business leaders, and other community members. They should also ensure the participation of children advocacy groups that work with their students and major employers of their students, as well as representatives of post-secondary institutions that serve their students."<a href="http://www.sedl.org/change/issues/issues23.html"></a>'],
    "vision":['The district, including the school board, the superintendent, key staff and influential stakeholders in the community, must have the capacity to develop and articulate both a vision and a set of practices that send a clear message of what schools are to be about. This is a message not only for educators, but for the community at large. This message creates public understanding of what the school system is trying to do to prepare more middle grades students for challenging high school work and to graduate more students from high school prepared for the next step'],
    "create_directory":['There are different approaches to identifying community assets. Each can be valid and useful. Which approach is right for you? The answer will depend in large part on your answers to the starting questions above.'],
    "provide_support":['Partners must be invested in a common vision and set of expectations for community schools.  This will help to sustain partnerships in the long run, enhance community school efficacy, and encourage each stakeholder to clearly define its role in meeting specific goals. District leaders, including superintendents and school boards, must work to ensure the initiatives results based vision is aligned and integrated with the districts overall school improvement plan and other core guidance documents. Community partners must adapt their mission to align with the community school vision.  Community schools and their partners also braid multiple funding streams to support their common vision. Title I funds as well as various private sources are often used to hire resource coordinators at individual school sites. Competitive grant funding from all levels of government provides important flexibility in meeting school site costs such as startup costs for a health clinic or expanding learning opportunities. Local foundations, local government, and others support the work of the intermediary and other community partners. Community schools use these and other funding sources to focus on sustainability and growth.'],
    "work_municipal":['School libraries facilitate the love of reading and have a major impact on each new generations development of the necessary skills for accessing and evaluating information. They also play an important role in instilling an appreciation for libraries that can last a lifetime. School libraries prepare students to become savvy users of college and university libraries and more passionate patrons of public libraries. As an important supply of next-generation users, public and academic libraries have a vested interest in strengthening the success of school libraries. Within a community, public and school libraries have many areas of overlapping interest. Students are almost always also patrons of the public library system. The public library system and the school district often draw their budgets from the same governmental entities that may be receptive to proposals for collaborative projects that can amplify the impact of allocated funds. Partnerships with schools represent an important channel of outreach for the public libraries. Schools benefit from access to resources, programs, and services beyond what they might otherwise be able to offer. Collaboration offers many opportunities for mutual benefit. Projects can address a variety of different issues or tasks. They can be formal or informal. Formal collaboration might include initiatives to share technical infrastructure, processes, or people. These projects promise the most impact and benefits, but require approval from the highest levels of administration, especially when reallocation of funding or other resources is involved. Individuals or units within these organizations can also work together more informally. Establishing and strengthening relationships among individuals who play similar roles within each separate organization can increase the awareness of their relative strengths and shortcomings. Ideas may emerge for initiatives that can be tried experimentally and that can be the basis for strategic or longer term alliances.'],
    "community_events":['School based health centers SBHCs are a powerful investment in the health and academic potential of children and adolescents. They provide access to services primary care, counseling, oral health, reproductive health, healthy eating, active living that enable children and adolescents to thrive in the classroom and beyond. SBHCs provide students access to health care in a location that is safe, convenient, and accessible, their school. They are staffed by licensed professionals with the experience and expertise to deliver quality care that addresses the broad range of concerns that affect students healthy development. The services SBHCs deliver improve the social, emotional, and behavioral health of students, as well as minimize the effects of poverty and other adverse experiences on their school success. Schools and SBHCs share the same mission they want their students to thrive. SBHCs integrate into the education environment by contributing directly to the schools mission and delivering outcomes that matter to educators such as reduced student absenteeism. SBHCs collaborate with school administrators, teachers, and support staff  to ensure the partnership meets student needs efficiently, effectively, and seamlessly.'],
    "support_transitions":['Complex school feeder patterns complicate student transitions. School feeder patterns are the paths that students take as they transition from lower to higher level schools. One school is said to feed into another if students from the originating school enroll in the next level school upon graduation. These feeder patterns can be important because they can affect the degree of dispersion among a student group as it transitions. The greater the number of schools sending students to a higher level school, the more these feeder patterns are considered complex.  As feeder patterns become more complex, it is increasingly challenging for staff from multiple schools to coordinate and communicate regarding transitions. Splitting groups of students who have spent many years together in the same elementary school at this time of transition may also increase their anxiety. Thus, feeder patterns may impact a students academic career. These patterns can be designed to largely move students together as a group or to disperse them among different schools as they move from one school level to the next.  Elk Grove simplified its feeder patterns by organizing its schools such that all students from a particular elementary school are strongly encouraged to go to the same middle grades school and then on to the same high school. Feeder school principals within Elk Grove collaborate to create a seamless educational experience from kindergarten through 12th grade. Respondents reported that this has not only simplified the feeder patterns, but has also fostered increased emphasis on graduation and post secondary enrollment.'],
    "enlist":['Assess Critical Needs:   If students or schools in your community have needs that are not being met or that are underfunded, the educational experience is likely to suffer. A school business partnership might provide a solution. Consider the type of partnership and the level of partnership that would best meet those needs ( direct funding, professional development, donation of goods or services, manpower, mentoring, etc.).  Also consider whether attempting to meet those needs with the help of an outside source is appropriate for your students and school.  Assess Potential Contributions: Conversely, businesses should take a close look at the range of contributions that can be offered to students and schools. Businesses with large numbers of employees, for example, might be able to offer substantial human resources for tutoring and mentoring efforts. Businesses with a strong technical capability, such as those in the computer or information services field, may be able to offer equipment and specific technical training. In every case, businesses and schools should work  together to match the most important needs to the potential contributions.'],
    "partner":['Youth, schools, and OST programs can all benefit from strong partnerships for learning. These partnerships can serve to strengthen, support, and even transform individual partners, resulting in improved program quality, more efficient use of resources, and better alignment of goals and curriculum.  At the heart of successful integrated learning opportunities are sound, sustainable partnerships among OST program providers and schools working together to support learning. While partnership development does not happen overnight, over time, effective partnerships move from being transactional to transformative in nature.10 That is, partners move from operating as separate entities with separate goals and outcomes to working in conjunction with one another to create an expanded learning system with a shared vision, mission, and outcomes. This study identified five strategies to support movement toward transformative, sustainable school OST partnerships: A.  A shared vision of student learning and success, with explicit focus on supporting academics.'],
    "curriculum_refinement":['Curriculum mapping is a process for collecting and recording curriculum related data that identifies core skills and content taught, processes employed, and assessments used for each subject area and grade level. The completed curriculum map then becomes a tool that helps teachers keep track of what has been taught and plan what will be taught.  Creating and working with curriculum maps is a 7-step process involving, Phase 1: Data collection. Phase 2: A review of all maps by all teachers. Phase 3: Small mixed group reviews, in which groups of five to eight diverse faculty members share individual findings Phase 4: Large group comparisons, in which all faculty members gather to examine the findings of the smaller groups. Phase 5: Identification of immediate revision points and creation of a timetable for resolution. Phase 6: Identification of points requiring additional research and planning, and a timetable for resolution of those points. Phase 7: Planning for the next review cycle <a href="http://www.educationworld.com/a_curr/virtualwkshp/curriculum_mapping.shtml">See more here</a>'],
    "asses_rigor":['Rigor is creating an environment in which each student is expected to learn at high levels, and each is supported so he or she can learn at high level, and each student demonstrates learning at high level.  (Blackburn, 2008).  By this definition, rigor requires high expectations, support, and a student product that allows students to demonstrate their learning.  In other words, we expect students to perform at high levels, yet we still provide support for these students.   Expectation and rigor can be very abstract concepts.  If we want our rigor to increase, we need to have a method to measure rigor.  In the past, we have used Bloom’s taxonomy to measure rigor.  Unfortunately, it is difficult to quantify Recall, Analyze, Create, etc.  Hess’s Cognitive Rigor Matrix combines Bloom’s and Webb’s Depth of Knowledge to produce a very effective tool for teachers and school leaders to measure the level of rigor in our classrooms.  <a href="http://www.educationworld.com/a_curr/virtualwkshp/curriculum_mapping.shtml">See more here</a>'],
    "ensure_vertical":['Curriculum coherence is in place when “policies, strategies, and content across subject areas and grade levels are consistent and aligned, reflect standards, and result in students, teachers, and parents positively perceiving the rationale, scope, and sequence of educational experiences” (Liebling 1997, 16). In Beane’s view: A “coherent” curriculum is one that holds together, that makes sense as a whole; and its parts, whatever they are, are unified and connected by that sense of the whole. The idea of coherence begins with a view of the curriculum as a broadly conceived concept as THE curriculum that is about “something.” It is not simply a collection of disparate parts or pieces that accumulate in student experiences and on transcripts. A coherent curriculum has a sense of the forest as well as the trees, a sense of unity and connectedness, of relevance and pertinence. Parts or pieces are connected or integrated in ways that are visible and explicit. There is a sense of a larger, compelling purpose, and actions are tied to that purpose (1995, online).<a href="http://www.warsaw.k12.in.us/information/document-library/2011-2012-strategic-planning-1/strategy-2-1/2051-curricular-alignment-1/file">See more here</a>'],
    "modifying_curriculum":['Modifying existing general curriculum has been an effective way to create more accessible learning environments to support all students and their teachers in various educational contexts. There are many terms in use regarding changes made to curriculum, such as enhancements, accommodations, overlapping, and adaptations.  The components of curriculum modification are well categorized by King-Sears (2001) into four types:  (a) accommodation, (b) adaptation, (c) parallel curriculum outcomes, and (d) overlapping curricula. Switlick (1997) explains that the purpose of modifying curriculum is “to enable an individual to compensate for intellectual, physical, or behavioral challenges” and to create learning environments which “allow the individual to use existing skill repertoires while promoting the acquisition of new skills and knowledge.<a href="http://aem.cast.org/binaries/content/assets/common/publications/aem/ncac-curriculum-modification-2014-12.docx.">See more here</a>'],
    "analyzing_student":['Looking Collaboratively at Student Work is a structured conversation where teachers use student work as a vehicle for learning and problem solving. During regular meetings, teachers use a protocol or structure to efficiently focus the discussion on the qualities of the student work. First considering what the work reveals about the student and the issues he/she cares about and then second to reflect on the relationship between the teacher’s goals and the student perspective. The process enables participants to collaboratively share and develop new ideas about the child as a learner, the learning environment, curriculum, and teaching. The conversation usually takes between 30 minutes and 60 minutes. There are four roles in the conversation: Facilitator, Presenting Educator, Documenter, and Participant. Roles rotate for each meeting so that all teachers take turns in each role. The last step of the conversation is for each person in the group to state what they learned from the conversation or what their next action step will be. Unlike other meetings and professional development that may or may not be relevant to a teacher’s current practice, the expectation for Looking Collaboratively at Student Work is that every teacher will benefit from this conversation every time.<a href="http://schools.nyc.gov/NR/rdonlyres/3C7CA389-AF66-4340-8248-314FF18FBFE6/0/LookingAtStudentWorkBLOGPOSTWDCBlogNov2010.pdf">See more here</a>'],
    "build_capacity":['Instruction should connect directly to students’ lives and must deeply engage them with the content in order for students to be better prepared for college and careers. To succeed in postsecondary education and in a 21st century economy, students must be afforded opportunities to practice higher-order thinking skills, such as how to analyze an argument, weigh evidence, recognize bias (their own and others’ bias), distinguish fact from opinion, balance competing principles, work collaboratively with others, and be able to communicate clearly what they understand (Wagner, 2006). In order to accomplish these goals, instruction must be rigorous and meaningful.  Teaching and learning approaches that involve students collaborating on projects that culminate with a product or presentation are a way to bring rigor into the classroom.  Students can take on real problems, use what they know and research to come up with real solutions to real  problems. They must engage with their subject and with their peers.<a href="https://dpi.wi.gov/sites/default/files/imce/cal/pdf/guiding-principles2.pdf">See more here</a>' ],
    "promote_voice":['To begin incorporating youth voices, educators should think beyond the student council, welcoming a range of student opinions in decisions about academic content, discipline, school culture, free time, the physical space of the school, and family partnerships. They should even consider an individual student’s wishes about which adults in the building will best teach and counsel him.  Brion-Meisels offers five ways schools can integrate student voices: 1. Regularly solicit student feedback. Educators can use surveys and other research methods to routinely gather data or ask students what’s happening in the hallways and bathrooms, how they feel about the content and structure of classes, and for suggestions on school policies, culture, and climate. 2. Engage students in studying and assessing their school. Beyond asking for feedback on questions created by adults, schools can train students in collecting and analyzing data. These youth researchers can then create their own research questions and use observations and feedback from peers to draw conclusions about what’s going right, what could be improved, and how to help. 3. Include authentic student representation on leadership teams. Principals should leave space for students on school leadership teams, improvement teams, or equity and diversity teams. In meetings, participants should treat students as full members of the team, not just observers. 4. Invite students to any discussion related to their own learning. Individual students need to be included in parent-teacher conferences, IEP meetings, student support meetings, discipline hearings any discussion in which they are the main topic. 5. More broadly, consider young people as stakeholders and partners in their schools. When school leaders set new goals or make a major decision, they should expect students to contribute. At the same time, educators should be willing to help students as they shape and achieve their own aspirations for their learning <a href="https://www.gse.harvard.edu/news/uk/16/08/giving-students-voice">See more here</a>'],
    "analyze_environment":['School culture affects everything that happens in a school, including student achievement. Although improving school culture is an often-touted goal, there have been few research-based tools to help principals and school improvement teams measure the health of their school’s culture. One of those tools, the School Culture Triage Survey see figure 1developed and refined by Phillips (1996), Phillips and Wagner (2002), and Wagner and Masden-Copas 2002 has been used by schools across the United States and Canada to quickly and accurately determine the present state of any school’s culture. Several researchers have used the survey and come to similar conclusions. Phillips (1996) conducted more than 3,100 school culture assessments from 1981 to 2006 and found compelling anecdotal evidence to suggest that the connection between school culture and student achievement is a reality and that culture influences everything that happens in a school. Phillips also found connections between school culture and staff member satisfaction, parent engagement, and community support<a href="http://www.mssaa.org/gen/mssaa_generated_bin/documents/basic_module/School_culture_triage.pdf">See more here</a>'],
    "inform_evaluations":['When assessment of teacher practices is transparent and openly collaborative, teachers can build professional communities and learn from one another. This process can only occur in non-threatening environments of formative assessment and growth.  Measures of teacher performance are most helpful and meaningful when they are based on multiple ratings and clear teaching standards in the formative growth process. Teachers need clear and actionable feedback based on standards for teaching and student learning that are comprehensive and transparent and on criterion-referenced assessments of teacher practice. Feedback is most useful as part of a comprehensive teacher development system. Summative evaluations of teachers should be based primarily on a single standard of effectiveness required for all teachers. After extensive support and intervention, a process to remove chronically ineffective teachers from the classroom, which guarantees due process measures, should commence. Integrated systems must link evaluation procedures with curricular standards, professional development activities, targeted support, and human capital decisions. Validated evaluation measures are essential. Measures of teacher effectiveness need to be based on widely accepted standards of teaching that attempt to capture a range of teaching behaviors, use multiple evaluation methods. <a href="http://www.nea.org/assets/docs/HE/TeachrAssmntWhtPaperTransform10_2.pdf">See more here</a>'],
    "embed_distributed":['In a distributed leadership model, responsibilities for providing feedback and support to teachers are shared by the principal and other school and/or district staff. This feedback may be given by a wide variety of educators—from peers to coaches to administrators—and be used formatively for self-reflection, collaborative planning, and/or formally used in evaluation. Implementing a distributed leadership approach creates an opportunity for districts to ensure all educators are receiving high quality feedback to improve their practice. Additionally, distributing leadership: 1. Builds a culture of trust, collegiality, and shared responsibility for all students; 2. Provides leadership opportunities for effective educators; and 3. Reduces evaluator workload. There are four broad approaches to distributing leadership: 1) Peer Assistance and Review: 2) Secondary Evaluators: 3) Instructional Coaches; and, 4) Collaborative Learning.<a href="http://www.doe.mass.edu/edeval/leadership/DistributedLeadershipIPG.pdf.">See more here</a>'],
    "learning_cycle":['Strong teaching practice is the foundation of an excellent school, and the learning cycle provides the organizing structure for improved practice. Schools that implement a coherent, unified approach to teacher professional learning often see gains in teacher effectiveness and subsequently, student learning. <a href="http://teacherleader.dpsk12.org/implementation-guide/increase-teacher-effectiveness-through-learning-cycles/.">See more here</a>'],
    "embrace_role":['The advantages of having educators and community builders work in tandem are many. Deep community–school relationships combine insider expertise with outside resources and support <a href="http://www.communityschools.org/assets/1/AssetManager/combuild_IEL.pdf">For further information please see the following</a> .'],
    "leadership_role":['Evaluation and mentoring of school professionals in the building is a vital and time-consuming part of each principal’s role. Because of these responsibilities, the principal plays a critical role in shaping the agendas for each building leadership team.<a href="http://www.niusileadscape.org/docs/FINAL_PRODUCTS/LearningCarousel/building_leadership_team.pdf">For further information please see the following</a>'],
    "community_mapping":['To function well, every system has to fully understand and manage its resources. Mapping is a first step toward enhancing essential understanding, and done properly, it is a major intervention in the process of moving forward with enhancing systemic effectiveness.<a href="http://smhp.psych.ucla.edu/pdfdocs/resourcemapping/resourcemappingandmanagement.pdf">See more here</a>'],
    "community_role":['Community engagement is a two-way street where the school, families, and the community actively work together, creating networks of shared responsibility for student success. It is a tool that promotes civic well being and that strengthens  the capacity of schools, families, and communities to support young peoples’ full development. Community engagement is the hallmark of a community school.  Principals paint a vibrant picture of community engagement: local community-based organizations and businesses working as partners with the school; community residents actively participating in the education of young people; advocates and community associations bringing resources to schools; and the school actively reaching out to be a resource to the community. Family involvement, too, is a part of community engagement. In a growing number of places, community engagement is the strategy for developing and sustaining a comprehensive community school.  when implemented effectively, community engagement reduces the weight that many principals have traditionally carried alone. The community school—schools that act as community hubs, focusing attention on academics as well as all the other factors that help young people succeed <a href="http://www.communityschools.org/assets/1/AssetManager/CommunityAndFamilyEngagement.pdf">See more here</a>'],
    "allocate_resources":['Social and emotional learning (SEL) can play an important role in supporting the goals of the five core elements of Safe Schools, Healthy Students (SS/HS) Initiatives. Realizing this potential calls for school leadership that both directs and publicly supports high-quality, school-wide SEL programming.  SEL is the term for the discipline that synthesizes converging research in these areas and the broader fields of child development, education, and neuroscience. SEL research demonstrates that systematically teaching social and emotional skills in school the skills of emotional intelligence results in greater caring, compassion, engagement, responsible behavior, and improved academic performance in students.  Research also demonstrates that SEL produces beneficial outcomes when it 1 helps students and adults become competent in the five core social and emotional areas self awareness, self management, social awareness, relationship skills, and responsible decision making) that enable students to make healthy decisions, resist inappropriate peer pressure, and succeed academically; and 2 creates caring and supportive school learning environments. <a href="http://www.promoteprevent.org/sites/www.promoteprevent.org/files/resources/leading_an_sel_school.pdf">See more here</a>'],
    "PIB":['School-wide positive behavior support (PBS) is a broad set of research-validated strategies designed to create school environments that promote and support appropriate behavior of all students. These environments are brought about through the identification of common behavioral expectations that are valued by the school community and can apply to all students in all school settings and situations.  PBS is predicated on the assumption that typical school discipline practices are ineffective for promoting and supporting desired behavior in school.   BEST PRACTICES: At the universal prevention level of PBS, procedures to address school-wide issues and a system to support student success must be developed. The universal system is designed for all students in a school building. The universal instructional system of PBS must address five critical features. Researchers at the OSEP Center on Positive Behavior Interventions and Supports (OSEP, 2004) have identified the core features of a school wide system as (a) establishing and defining clear and consistent school-wide expectations, (b) teaching the school-wide expectations to students, (c) acknowledging students for demonstrating the expected behaviors, (d) developing a clear and consistent consequence system to respond to behavioral violations, and (e) using data to evaluate the impact of school wide efforts. <a href="https://www.thewatsoninstitute.org/nu_upload/files/PBIS%20Best%20Practices.pdf">See more here</a>'],
    "address_needs":['School social workers provide mental health services in schools and have specialized training to meet students’ social-emotional needs. Schools often are one of the first places where mental health issues are recognized and addressed (Hennessy & Green-Hennessey, 2000; Hoagwood et al., 2005). School social workers serve as the primary mental health providers for students and may be the only counseling professionals available to students and their families to initially identify and provide interventions for those issues. (Early&Vonk, 2001; Hennessy & Green-Hennessy, 2000; Kelly, Berzin, et al., 2010). In a 2008 survey of school social workers, only 11 percent of respondents reported all or most students on their caseloads received counseling or therapeutic services outside of school (Kelly, Berzin, et al., 2010). School social workers design and implement school-based programs to promote a positive school climate among all students. They work with the entire student body to identify students in need of more intensive interventions and connect these students to additional services in the community where needed. School social workers serve as a resource to the principal and other educators, providing consultation and training on identifying students with mental health needs and a referral process when services are sought. Working more closely with individual students and their families, school social workers also create a bridge between the school and the community when linking such services. This coordination is critical in a successful school and community partnership to maximize limited resources, facilitate better service delivery, and maintain communication between partners.<a href="http://www.sswaa.org/?600">See more here</a>'],
    "implement_school":['School based mental health programs, to be most effective, must be correctly constructed. While they may vary from school to school, there are some key characteristics consistent across all of them. School-based programs will not be effective unless there is collaboration and relationship building among parents, teachers, administrators, community mental health professionals, and students. An infrastructure, process, and clearly defined roles must be painstakingly developed to address the varying needs of the student body. And the program must have the right team members, who bring unique skill sets and experiences to the endeavor.  School districts benefit from teaming with community mental health providers who have unique competencies, such as integrated substance abuse and mental health services for youths; family, individual, and group therapies; medication management; case management; and an orientation toward assertive community outreach principals. When complex interventions are needed, often under extreme crisis situations, schools will need to quickly mobilize a mental health team that brings a wide range of specialties to any situation. Most schools don’t have the capacity or adequate staff on site to respond to (or anticipate) a situation that requires skilled crisis intervention, evaluation, medication management, and other services that a contracted team should.<a href="http://www.socialworktoday.com/archive/111312p24.shtml">See more here</a>' ],
    "receive_guidance":['School counselors are uniquely positioned as the school professionals best able to guide all students toward college readiness. School counselors interact with teachers, administrators, students and their families  each day, marshaling forces from across the school, district and community. School counselors are leaders  and advocates who can profoundly influence students academic achievement, aspirations, decisions and future plans. They are school-based professionals who connect students to resources and information about preparing for and applying to college.  The Eight Components of College and Career Readiness Counseling (College Aspirations; Academic Planning for College and Career Readiness; and Enrichment and Extracurricular Engagement, etc.)  provide a systemic approach for school counselors to implement, across grades K 12 elementary through high school and beyond, to ensure equity both in process and results. <a href="https://secure-media.collegeboard.org/digitalServices/pdf/nosca/11b_4416_8_Components_WEB_111107.pdf">See more here</a>'],
    "dropout_prevention":['Successful Schools can implement the following. 1. Stay focused on improving student engagement through curriculum, instruction, academic and student support interventions, career development, climate, and safety initiatives 2. Work hard improving student attendance, in a systematic way, throughout the year and over the years 3. Address the different forms of attendance problems the school is evidencing: o Absences o Tardiness o Class skipping o Suspension/Expulsion 4. Use a tiered intervention structure -- a continuum of strategies and practices: o Prevention for all students, establishing expectations and positive school climate; fair policies and procedures, o Early Intervention for students on the verge of evidencing significant attendance problems -- Address barriers to attendance with targeted interventions specific to students o Intensive Intervention for students evidencing patterns of chronic attendance problems.<a href="http://www.schoolturnaroundsupport.org/sites/default/files/resources/Improving_Attendance05112012.pdf">See more here</a>'],
    "aware_res":['All States, the District of Columbia, and U.S. territories have reporting statutes for child abuse and neglect. These statutes outline who must report, to whom the abuse or neglect must be reported, and the form and content of the report. Given the diversity of statutes, educators should be familiar with or obtain a copy of the law in their State.    Most States specifically require educators to report suspected child maltreatment unless educators are grouped under the category of “anyone.” Some States specifically define what is meant by an “educator” (e.g., teachers, principals, administrators, school nurses, school social workers, and guidance counselors) in any school, whether public or private, day or residential. Those professionals mandated to report vary from State to State. Educators should check their State reporting statute to determine who has been designated as a mandated reporter. They also should be familiar with their school system’s policy and procedures regarding child abuse and neglect reporting. Additionally, it should be noted that when schools have a Child Protection Team, an educator’s report to the team may or may not free him or her from further obligation, and a child protective services (CPS) caseworker may still contact him or her. The Child Protection Team representative would make the actual report to CPS. This regulation also should be researched within the educator’s own State. <a href="https://www.childwelfare.gov/pubPDFs/educator.pdf">See more here</a>'],
    "align_youth":['A community school is both a place and a set of partnerships between the school and other community resources. Its integrated focus on academics, health and social services, youth and community development and community engagement leads to improved student learning, stronger families and healthier communities. Community schools offer a personalized curriculum that emphasizes real-world learning and community problem-solving. Schools become centers of the community and are open to everyone – all day, every day, evenings and weekends.  Using public schools as hubs, community schools bring together many partners to offer a range of supports and opportunities to children, youth, families and communities. Partners work to achieve these results: Children are ready to enter school; students attend school consistently; students are actively involved in learning and their community; families are increasingly involved with their childrens education; schools are engaged with families and communities; students succeed academically; students are healthy physically, socially, and emotionally; students live and learn in a safe, supportive, and stable environment, and communities are desirable places to live.<a href="http://www.communityschools.org/aboutschools/what_is_a_community_school.aspx">See more here</a>'],
    "cultivate_knowledge":['The concept of Social and Emotional Learning (SEL) is grounded in the field of positive youth development which upholds that the needs of youth must be addressed by creating environments or settings that promote outcomes like school achievement, mutually supportive relationships with adults and peers, problem solving, and civic engagement (Catalano et al., 2004; Greenberg et al., 2003).  Efforts to promote positive youth development differ from those aimed at reducing risk factors in that they are focused on enhancing skills, building assets, and promoting resilience to achieve positive outcomes (Catalano, Hawkins, Berglund, Pollard, & Arthur, 2002). Positive youth development interventions like SEL programming typically utilize a skill-building, whole-child approach that is focused on cultivating assets, not on preventing problems. Schools are predominant settings that serve the educational and developmental needs of youth, and thus are compelling targets for universal efforts to promote positive youth development.  To accomplish this broader educational agenda, school-based programming needs to meet two standards: (1) enhance the social and emotional assets and learning of students across the curriculum, and (2) improve the quality of the environments in which academic, social, and emotional learning occurs (Greenberg et al., 2003; Zigler & Bishop-Josef, 2006; Zins, Elias, Greenberg, & Weissberg, 2000).<a href="http://ei.yale.edu/wp-content/uploads/2013/09/Transforming-Students%E2%80%99-Lives-with-Social-and-Emotional-Learning.pdf">See more here</a>'],
    "provide_time":['While it’s impossible to always keep up with all the new technological classroom trends, there are certain lesson planning basics teachers need even before they know what they are going to teach. Here are five suggestions for planning a successful media based lesson.  Tip 1. Start Small:  While there are endless possibilities on how to engage students, we also need to feel comfortable with whatever digital technological media we are using.  Stick to the technological type that best suits you and your personality and your students’ learning needs. However, If you are obligated by your school to use a Smartboard, accept your destiny peacefully for the time being and learn from the experiences.  Tip 2. Learn: Here’s an important but tricky tip. LEARN the new technology as often as possible. As you do, get into the heads of your students by critically evaluate the products. Anticipate any problems your students and yourself might encounter and quickly write them down. Ask other teachers how they cope. There’s nothing better than making an informed decision.<a href="http://teaching.monster.com/benefits/articles/8058-5-lesson-planning-tips-for-incorporating-technology">See more here</a>'],
    
                 
                       
                       
                       
                       
                   #  <a href="http://www.nea.org/assets/docs/HE/TeachrAssmntWhtPaperTransform10_2.pdf">See more here</a>']
                       
                       
                       
                       
                       
                       
}
import datetime
mapping = {
    "now":datetime.datetime.now(),
    "tomorrow": datetime.date.today() + datetime.timedelta(days=1),
    "today":datetime.date.today(),
    "same time":datetime.datetime.now(),
    "second day":datetime.datetime.now()
}

def try_parsing_date(text):
    """
    Parses time of string format to a time object
    """
    for fmt in ('%I %p', '%I %M %p', '%I:%M %p'):
        try:
            return datetime.datetime.strptime(text, fmt)
        except ValueError:pass
    if ":" in text:
        return datetime.datetime.strptime(text+" "+
                ("AM" if int(text.split(":")[0])>=8 else "PM"), '%I:%M %p')
    return datetime.datetime.strptime(text+" "+
            ("AM" if int(text)>=8 else "PM"), '%I %p')

def get_date_time(day,time):
    """
    Maps words like now today tom etc., to corresponding datetime objects
    """
    try:time = mapping[time]
    except KeyError:
        if not time:
            time = datetime.datetime.now()
        else:
            time = try_parsing_date(time)
    try:date = mapping[day]
    except KeyError:date = datetime.date.today()

    return datetime.datetime.combine(date, time.time())
